project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Yumou Wang (王予谋)"
  site-url: https://brooks.github.io
  favicon: static/img/favicon.jpg
  repo-url: https://github.com/BrooksGan/brooks.github.io
  # repo-actions: [edit, issue]
  
  page-footer:
    left: |
      HKU Yumou
    right: |
      Made with [Quarto](https://quarto.org/)<br>    
  navbar: 
    background: "#000000"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research/index.qmd # blogs        
      # - text: "Publications"
      #   href: publications.qmd # blogs
      # - text: "Working Papers"
      #   href: Working Papers.qmd # books
      - text: "Teaching"
        href: Teaching.qmd # blog
      - text: "Resources"
        href: Resources.qmd # codes
      - text: "CV"
        href: CV.pdf

format:
  html:
    theme: custom.scss # styles
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细